//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenedor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        public Ciudad()
        {
            this.Comuna = new HashSet<Comuna>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IdCiudad { get; set; }
        public string NombreCiudad { get; set; }
        public int IdRegion { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<Comuna> Comuna { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
