//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenedor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comuna
    {
        public Comuna()
        {
            this.Sucursal = new HashSet<Sucursal>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IdComuna { get; set; }
        public string NombreComuna { get; set; }
        public int IdCiudad { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
