//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenedor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        public Contrato()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IdContrato { get; set; }
        public string TipoContrato { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
