//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenedor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Producto
    {
        public int IdProducto { get; set; }
        [Required(ErrorMessage = "Campo obligatorio", AllowEmptyStrings = false)]
        public string NombreProducto { get; set; }
        [Required(ErrorMessage = "Campo obligatorio", AllowEmptyStrings = false)]
        [Positivo(ErrorMessage = "El stock disponible debe ser positivo")]
        public int StockDisponible { get; set; }
        [Required(ErrorMessage = "Campo obligatorio", AllowEmptyStrings = false)]
        [Positivo(ErrorMessage = "El stock total debe ser positivo")]
        public int StockTotal { get; set; }
        [Required(ErrorMessage = "Campo obligatorio", AllowEmptyStrings = false)]
        [Positivo(ErrorMessage = "El precio del producto debe ser positivo")]
        public int Precio { get; set; }
        public int IdCategoria { get; set; }
        public int IdSucursal { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
    
    public class Positivo : ValidationAttribute
    {
        public override bool IsValid(object value)
        {
            if (value == null)
            {
                return true;
            }
            int getal;
            if (int.TryParse(value.ToString(), out getal))
            {
                if (getal >= 0)
                    return true;
            }
            return false;
        }
    }
}
